In [3]:
import pandas as pd

In [4]:
##Q1. Pandas Series
# marks = [78, 85, 92, 66, 88]
# expected output:
# 0    78
# 1    85
# 2    92
# 3    66
# 4    88

marks = [78, 85, 92, 66, 88]
pd.Series(marks)

0    78
1    85
2    92
3    66
4    88
dtype: int64

In [5]:
# Q2. Custom Index
# marks = [78, 85, 92, 66, 88]
# students = ["Navya", "Ramu", "Rohit", "Priya", "Sai"]
# Expected Output:
# Navya     78
# Ramu      85
# Rohit     92
# Priya     66
# Sai       88

marks = [78, 85, 92, 66, 88]
students = ["Navya", "Ramu", "Rohit", "Priya", "Sai"]
pd.Series(marks, index = students)

Navya    78
Ramu     85
Rohit    92
Priya    66
Sai      88
dtype: int64

In [6]:
# Q3. Series datatype change
# salary = [25000, 30000, 45000, 50000]
# Expected Output:
# 25000.0
# 30000.0
# 45000.0
# 50000.0

salary = [25000, 30000, 45000, 50000]
pd.Series(salary, dtype= float)

0    25000.0
1    30000.0
2    45000.0
3    50000.0
dtype: float64

In [7]:
# Q4. Dictionary → Series
employee_salary = {
    "E101": 25000,
    "E102": 32000,
    "E103": 41000,
    "E104": 28000
}
pd.Series(employee_salary)  #keys become index numbers

E101    25000
E102    32000
E103    41000
E104    28000
dtype: int64

In [8]:
# Q5. Employee DataFrame
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Arjun", "Meena", "Rahul", "Divya", "Kiran"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [30000, 28000, 45000, 50000, 35000]
}
df = pd.DataFrame(data)
df

   Employee_ID   Name Department  Salary
0          101  Arjun         IT   30000
1          102  Meena         HR   28000
2          103  Rahul         IT   45000
3          104  Divya    Finance   50000
4          105  Kiran         HR   35000

In [9]:
#Q6. Single column access
df['Salary']

0    30000
1    28000
2    45000
3    50000
4    35000
Name: Salary, dtype: int64

In [10]:
#Q7. Multiple columns access
df[['Name']+['Salary']]

    Name  Salary
0  Arjun   30000
1  Meena   28000
2  Rahul   45000
3  Divya   50000
4  Kiran   35000

In [11]:
# Column-wise Operations
# Q8. Salary Hike
df['Hike'] = df['Salary']*20/100
df['New_Salary'] = df['Salary'] + df['Hike']
df

   Employee_ID   Name Department  Salary     Hike  New_Salary
0          101  Arjun         IT   30000   6000.0     36000.0
1          102  Meena         HR   28000   5600.0     33600.0
2          103  Rahul         IT   45000   9000.0     54000.0
3          104  Divya    Finance   50000  10000.0     60000.0
4          105  Kiran         HR   35000   7000.0     42000.0

In [12]:
#Q9. Dataset
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

   Employee_ID   Name Department  Salary     Hike  New_Salary
0          101  Arjun         IT   30000   6000.0     36000.0
1          102  Meena         HR   28000   5600.0     33600.0
2          103  Rahul         IT   45000   9000.0     54000.0
3          104  Divya    Finance   50000  10000.0     60000.0
4          105  Kiran         HR   35000   7000.0     42000.0
   Employee_ID   Name Department  Salary     Hike  New_Salary
0          101  Arjun         IT   30000   6000.0     36000.0
1          102  Meena         HR   28000   5600.0     33600.0
2          103  Rahul         IT   45000   9000.0     54000.0
3          104  Divya    Finance   50000  10000.0     60000.0
4          105  Kiran         HR   35000   7000.0     42000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Department   5 non-null      object
 3   Salary       5 non-null      int64
 4   Hike         5 non-null      float64
 5   New_Salary   5 non-null      float64
dtypes: float64(2), int64(2), object(2)
memory usage: 372.0+ bytes
None
       Employee_ID        Salary         Hike    New_Salary
count     5.000000      5.000000      5.00000      5.000000
mean    103.000000  37600.000000   7520.00000  45120.000000
std       1.581139   9555.103348   1911.02067  11466.124018
min     101.000000  28000.000000   5600.00000  33600.000000
25%     102.000000  30000.000000   6000.00000  36000.000000
50%     103.000000  35000.000000   7000.00000  42000.000000
75%     104.000000  45000.000000   9000.00000  54000.000000
max     105.000000  50000.000000  10000.00000  60000.000000

In [13]:
#Filtering
# Q10. Salary filter
print(df[df.Salary>=35000])

   Employee_ID   Name Department  Salary     Hike  New_Salary
2          103  Rahul         IT   45000   9000.0     54000.0
3          104  Divya    Finance   50000  10000.0     60000.0
4          105  Kiran         HR   35000   7000.0     42000.0

In [14]:
# Q11. Filter + Specific columns
df1 = (df[df.Salary>=35000])
print(df1[['Employee_ID', 'Name', 'Salary']])

   Employee_ID   Name  Salary
2          103  Rahul   45000
3          104  Divya   50000
4          105  Kiran   35000

In [15]:
# loc Practice
# Q12. loc basic
print(df)
df.index = ["EMP101", "EMP102", "EMP103", "EMP104", "EMP105"]
print(df)
df.loc["EMP103", "Salary"]

   Employee_ID   Name Department  Salary     Hike  New_Salary
0          101  Arjun         IT   30000   6000.0     36000.0
1          102  Meena         HR   28000   5600.0     33600.0
2          103  Rahul         IT   45000   9000.0     54000.0
3          104  Divya    Finance   50000  10000.0     60000.0
4          105  Kiran         HR   35000   7000.0     42000.0
        Employee_ID   Name Department  Salary     Hike  New_Salary
EMP101          101  Arjun         IT   30000   6000.0     36000.0
EMP102          102  Meena         HR   28000   5600.0     33600.0
EMP103          103  Rahul         IT   45000   9000.0     54000.0
EMP104          104  Divya    Finance   50000  10000.0     60000.0
EMP105          105  Kiran         HR   35000   7000.0     42000.0

np.int64(45000)

In [16]:
#Q13. Multiple data using loc

df.loc["EMP102":"EMP104",['Employee_ID','Name', 'Salary']]

        Employee_ID   Name  Salary
EMP102          102  Meena   28000
EMP103          103  Rahul   45000
EMP104          104  Divya   50000

In [17]:
# iloc Practice
# Q14. iloc basic
df.iloc[2,3]

np.int64(45000)

In [18]:
#Q15. iloc slicing
df.iloc[:3,:3]

        Employee_ID   Name Department
EMP101          101  Arjun         IT
EMP102          102  Meena         HR
EMP103          103  Rahul         IT

In [30]:
#Missing Values Practice
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Arjun", "Meena", np.nan, "Divya", "Kiran"],
    "Department": ["IT", "HR", "IT", np.nan, "HR"],
    "Salary": [30000, 28000, np.nan, 50000, 35000]
}

df21 = pd.DataFrame(data)
df21

   Employee_ID   Name Department   Salary
0          101  Arjun         IT  30000.0
1          102  Meena         HR  28000.0
2          103    NaN         IT      NaN
3          104  Divya        NaN  50000.0
4          105  Kiran         HR  35000.0

In [31]:
#Q16. identify Missing values
df21.isnull()

   Employee_ID   Name  Department  Salary
0        False  False       False   False
1        False  False       False   False
2        False   True       False    True
3        False  False        True   False
4        False  False       False   False

In [32]:
#Q17. Null count
df21.isnull().sum()

Employee_ID    0
Name           1
Department     1
Salary         1
dtype: int64

In [37]:
#Q18. Fill Salary missing value
#Q19. Fill missing value for Different columns
df21["Salary"] = df21["Salary"].fillna(df21["Salary"].mean())
df21["Name"] = df21["Name"].fillna("Unknown")
df21["Department"] = df21["Department"].fillna("Not Assigned")
df21

   Employee_ID     Name    Department   Salary
0          101    Arjun            IT  30000.0
1          102    Meena            HR  28000.0
2          103  Unknown            IT  35750.0
3          104    Divya  Not Assigned  50000.0
4          105    Kiran            HR  35000.0

In [48]:
# dropna / drop
# Q20. dropna()
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Arjun", "Meena", np.nan, "Divya", "Kiran"],
    "Department": ["IT", "HR", "IT", np.nan, "HR"],
    "Salary": [30000, 28000, np.nan, 50000, 35000]
}

df22 = pd.DataFrame(data)
print(df22)
df22 = df22.dropna()
df22

   Employee_ID   Name Department   Salary
0          101  Arjun         IT  30000.0
1          102  Meena         HR  28000.0
2          103    NaN         IT      NaN
3          104  Divya        NaN  50000.0
4          105  Kiran         HR  35000.0

   Employee_ID   Name Department   Salary
0          101  Arjun         IT  30000.0
1          102  Meena         HR  28000.0
4          105  Kiran         HR  35000.0

In [49]:
#Q21. inplace=True - removes the Nan value rows permanently
df22

   Employee_ID   Name Department   Salary
0          101  Arjun         IT  30000.0
1          102  Meena         HR  28000.0
4          105  Kiran         HR  35000.0

In [52]:
#Insert / Pop / Delete
# Q22. Column insert
print(df)
location = ['Hyderabad', 'Pune', 'Bangalore', 'Chennai', 'Mumbai']
df.insert(3, "Location", location)
print(df)

        Employee_ID   Name Department  Salary     Hike  New_Salary
EMP101          101  Arjun         IT   30000   6000.0     36000.0
EMP102          102  Meena         HR   28000   5600.0     33600.0
EMP103          103  Rahul         IT   45000   9000.0     54000.0
EMP104          104  Divya    Finance   50000  10000.0     60000.0
EMP105          105  Kiran         HR   35000   7000.0     42000.0
        Employee_ID   Name Department   Location  Salary     Hike  New_Salary
EMP101          101  Arjun         IT  Hyderabad   30000   6000.0     36000.0
EMP102          102  Meena         HR       Pune   28000   5600.0     33600.0
EMP103          103  Rahul         IT  Bangalore   45000   9000.0     54000.0
EMP104          104  Divya    Finance    Chennai   50000  10000.0     60000.0
EMP105          105  Kiran         HR     Mumbai   35000   7000.0     42000.0

In [53]:
#Q23. pop()
removed_department = df.pop("Department")
print(df)
print(removed_department)

        Employee_ID   Name   Location  Salary     Hike  New_Salary
EMP101          101  Arjun  Hyderabad   30000   6000.0     36000.0
EMP102          102  Meena       Pune   28000   5600.0     33600.0
EMP103          103  Rahul  Bangalore   45000   9000.0     54000.0
EMP104          104  Divya    Chennai   50000  10000.0     60000.0
EMP105          105  Kiran     Mumbai   35000   7000.0     42000.0
EMP101         IT
EMP102         HR
EMP103         IT
EMP104    Finance
EMP105         HR
Name: Department, dtype: object

In [58]:
#Q24. Delete column
del df["Location"]
print(df)

        Employee_ID   Name  Salary     Hike  New_Salary
EMP101          101  Arjun   30000   6000.0     36000.0
EMP102          102  Meena   28000   5600.0     33600.0
EMP103          103  Rahul   45000   9000.0     54000.0
EMP104          104  Divya   50000  10000.0     60000.0
EMP105          105  Kiran   35000   7000.0     42000.0

In [1]:
#PART-B Dataset creation
import pandas as pd
import numpy as np

employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": [
        "Arjun", "Meena", "Rahul", "Divya",
        "Kiran", "Sneha", "Vijay", "Anjali"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "HR"
    ],
    "Employment_Type": [
        "Permanent", "Contract", "Permanent", "Permanent",
        "Contract", "Permanent", "Contract", "Permanent"
    ],
    "Country": [
        "India", "India", "USA", "India",
        "Germany", "USA", "India", "Germany"
    ],
    "Salary": [
        50000, 35000, 60000, 55000,
        38000, 52000, 45000, 42000
    ],
    "Experience": [5, 2, 7, 6, 3, 5, 4, 3]
}

df = pd.DataFrame(employee_data)

print(df)

   Employee_ID    Name Department Employment_Type  Country  Salary  Experience
0          101   Arjun         IT       Permanent    India   50000           5
1          102   Meena         HR        Contract    India   35000           2
2          103   Rahul         IT       Permanent      USA   60000           7
3          104   Divya    Finance       Permanent    India   55000           6
4          105   Kiran         HR        Contract  Germany   38000           3
5          106   Sneha    Finance       Permanent      USA   52000           5
6          107   Vijay         IT        Contract    India   45000           4
7          108  Anjali         HR       Permanent  Germany   42000           3

In [3]:
#25. groupby()
dff = df.groupby("Department")["Salary"].mean()
dff

Department
Finance    53500.000000
HR         38333.333333
IT         51666.666667
Name: Salary, dtype: float64

In [4]:
df.groupby("Department")["Employee_ID"].count()

Department
Finance    2
HR         3
IT         3
Name: Employee_ID, dtype: int64

In [5]:
df.groupby("Department")["Salary"].agg(
    ["min", "max", "mean", "sum"]
)

              min    max          mean     sum
Department
Finance     52000  55000  53500.000000  107000
HR          35000  42000  38333.333333  115000
IT          45000  60000  51666.666667  155000

In [6]:
#transpose
df.T

,0,1,2,3,4,5,6,7
Employee_ID,101,102,103,104,105,106,107,108
Name,Arjun,Meena,Rahul,Divya,Kiran,Sneha,Vijay,Anjali
Department,IT,HR,IT,Finance,HR,Finance,IT,HR
Employment_Type,Permanent,Contract,Permanent,Permanent,Contract,Permanent,Contract,Permanent
Country,India,India,USA,India,Germany,USA,India,Germany
Salary,50000,35000,60000,55000,38000,52000,45000,42000
Experience,5,2,7,6,3,5,4,3

In [7]:
print(df.shape)
print(df.T.shape)

(8, 7)
(7, 8)