In [ ]:
a'''
What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.


Pandas : Powerful for data analysis

Pandas stands for “Python Data Analysis Library”
Data wrangling —also called data cleaning, data remediation,
or data munging

'''

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1200px-Pandas_logo.svg.png">


<img src="https://static.javatpoint.com/tutorial/pandas/images/python-pandas-dataframe.png">

In [ ]:
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)

In [ ]:
'''
What is a Series?
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.
'''
s1 = pd.Series([23,24,25,12,24])
s1

0    23
1    24
2    25
3    12
4    24
dtype: int64

<img src="https://1.bp.blogspot.com/-AkAiqQBMhvM/XJiYR2xWg-I/AAAAAAAAAIo/wXoFEgnKbhQbpEy_o5XxAYY5uA0y97hOQCLcBGAs/w1200-h630-p-k-no-nu/pandas-powerful-data-analysis-tools-for-python-13-638.jpg">

In [ ]:
s2 = pd.Series([23,45,67,12,34],index = ['a','b','c','d','e'])
s2

a    23
b    45
c    67
d    12
e    34
dtype: int64

In [ ]:
s3 = pd.Series([23,45,67,12,34],index = ['a','b','c','d','e'],dtype = 'float')
s3

a    23.0
b    45.0
c    67.0
d    12.0
e    34.0
dtype: float64

### creation of Series using dictionary

In [ ]:
s4 = pd.Series({'e':65,'f':43,'c':45})
s4

e    65
f    43
c    45
dtype: int64

### DataFrame
What is a DataFrame?
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

<img src="https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png">

In [ ]:
# @title
d1 = pd.DataFrame([43,54,65,76])
d1

    0
0  43
1  54
2  65
3  76

In [ ]:
d2 = pd.DataFrame([[2,3,4],
                   [4,5,6],
                   [1,2,3]])
d2

   0  1  2
0  2  3  4
1  4  5  6
2  1  2  3

In [ ]:
d2 = pd.DataFrame(s2)  #converting series into dataframe
d2

    0
a  23
b  45
c  67
d  12
e  34

In [ ]:
d3  = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'])
d3

   a  b  c
0  2  3  4
1  4  5  6
2  1  2  3

In [ ]:
d3  = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'],index = ['x','y','z'])
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

### creating DataFrame from list of dictionaries

In [ ]:
dic = [{'alex':1,'joe':2},{'ema':5,'dora':10,'alice':20},{'ema':5,'dora':10,'alice':20}]
pd.DataFrame(dic,index=['a','b','c'])

   alex  joe  ema  dora  alice
a   1.0  2.0  NaN   NaN    NaN
b   NaN  NaN  5.0  10.0   20.0
c   NaN  NaN  5.0  10.0   20.0

### DataFrame operations

In [ ]:
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [ ]:
print(d3['a'])
print(d3['b'])

x    2
y    4
z    1
Name: a, dtype: int64
x    3
y    5
z    2
Name: b, dtype: int64

In [ ]:
d3['d']=d3['a']*d3['b']
d3['e']=d3['a']+d3['d']
d3

   a  b  c   d   e
x  2  3  4   6   8
y  4  5  6  20  24
z  1  2  3   2   3

In [ ]:
pop = d3.pop('b')
d3

   a  c   d   e
x  2  4   6   8
y  4  6  20  24
z  1  3   2   3

In [ ]:
d3

   a  c   d   e
x  2  4   6   8
y  4  6  20  24
z  1  3   2   3

In [ ]:
del d3['d']

In [ ]:
d3

   a  c   e
x  2  4   8
y  4  6  24
z  1  3   3

In [ ]:
d3.pop('a')
d3

   c   e
x  4   8
y  6  24
z  3   3

In [ ]:
d3.insert(2,'new1',[45,52,66]) #(loc,col,data)
d3

   c   e  new1
x  4   8    45
y  6  24    52
z  3   3    66

In [ ]:
d={'c':1,'new1':33,'e':22}
df11=d3._append(d,ignore_index=True)
df11

   c   e  new1
0  4   8    45
1  6  24    52
2  3   3    66
3  1  22    33

In [ ]:
import numpy as np
d4 = pd.DataFrame({'abc':np.random.randint(2,6,size=(10)),'bcd':np.random.randint(4,10,size=(10)),'cde':np.random.randint(3,10,size=(10))})
d4

   abc  bcd  cde
0    5    9    8
1    5    4    7
2    3    9    5
3    2    7    5
4    3    5    5
5    4    5    8
6    5    7    4
7    4    6    9
8    5    6    8
9    2    7    9

In [ ]:
d4.head()

   abc  bcd  cde
0    5    9    8
1    5    4    7
2    3    9    5
3    2    7    5
4    3    5    5

In [ ]:
d4.tail()

   abc  bcd  cde
5    4    5    8
6    5    7    4
7    4    6    9
8    5    6    8
9    2    7    9

In [ ]:
'''
Info About the Data
The DataFrames object has a method called info(),that gives you more information about the data set.'''
d4.info()
d4.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   bcd     10 non-null     int64
 2   cde     10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

             abc        bcd        cde
count  10.000000  10.000000  10.000000
mean    3.800000   6.500000   6.800000
std     1.229273   1.649916   1.873796
min     2.000000   4.000000   4.000000
25%     3.000000   5.250000   5.000000
50%     4.000000   6.500000   7.500000
75%     5.000000   7.000000   8.000000
max     5.000000   9.000000   9.000000

In [ ]:
d4

   abc  bcd  cde
0    5    9    8
1    5    4    7
2    3    9    5
3    2    7    5
4    3    5    5
5    4    5    8
6    5    7    4
7    4    6    9
8    5    6    8
9    2    7    9

In [ ]:
print(d4.loc[0,'cde']) #loc[row name,colname]

8

In [ ]:
d4

   abc  bcd  cde
0    5    9    8
1    5    4    7
2    3    9    5
3    2    7    5
4    3    5    5
5    4    5    8
6    5    7    4
7    4    6    9
8    5    6    8
9    2    7    9

In [ ]:
d4.loc[4:9,['abc','cde']]

   abc  cde
4    3    5
5    4    8
6    5    4
7    4    9
8    5    8
9    2    9

In [ ]:
d4.loc[[3,4,7],['abc','cde']]

   abc  cde
3    2    5
4    3    5
7    4    9

In [ ]:
d4

   abc  bcd  cde
0    5    9    8
1    5    4    7
2    3    9    5
3    2    7    5
4    3    5    5
5    4    5    8
6    5    7    4
7    4    6    9
8    5    6    8
9    2    7    9

<img src='https://www.marsja.se/wp-content/uploads/2019/09/pandas_select_row_by_index_iloc.png'>

In [ ]:
print(d4.iloc[2,1])  #[row index,column index]

9

In [ ]:
d4.iloc[4:9,[0,2]]

   abc  cde
4    3    5
5    4    8
6    5    4
7    4    9
8    5    8

In [ ]:
d4

   abc  bcd  cde
0    5    9    8
1    5    4    7
2    3    9    5
3    2    7    5
4    3    5    5
5    4    5    8
6    5    7    4
7    4    6    9
8    5    6    8
9    2    7    9

In [ ]:
d4.abc

0    5
1    5
2    3
3    2
4    3
5    4
6    5
7    4
8    5
9    2
Name: abc, dtype: int64

In [ ]:
d4.abc.values # data frame . column .values

array([5, 5, 3, 2, 3, 4, 5, 4, 5, 2])

In [ ]:
d4['sub'] = d4.abc.values - d4.cde.values - d4.bcd.values
d4

   abc  bcd  cde  sub
0    5    9    8  -12
1    5    4    7   -6
2    3    9    5  -11
3    2    7    5  -10
4    3    5    5   -7
5    4    5    8   -9
6    5    7    4   -6
7    4    6    9  -11
8    5    6    8   -9
9    2    7    9  -14

In [ ]:
a = [['rk',102,15000],['rama',103,20000],['krishna',104,25000]]
dfl = pd.DataFrame(a,columns = ['name','id','salary'])
dfl

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000

In [ ]:
y=dfl[dfl.salary>=20000]
print(y)
y[['id','salary']]

      name   id  salary
1     rama  103   20000
2  krishna  104   25000

    id  salary
1  103   20000
2  104   25000

In [ ]:
dfl._append({'name' : 'aravind','id' : 105,'salary' : 30000},ignore_index=True)

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3  aravind  105   30000

In [ ]:
dfl = dfl._append({'name' : np.nan,'id' : 105,'salary' : 30000},ignore_index = True)
dfl

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [ ]:
dfl.isnull()

    name     id  salary
0  False  False   False
1  False  False   False
2  False  False   False
3   True  False   False

In [ ]:
print(dfl.isnull().sum())

name      1
id        0
salary    0
dtype: int64

In [ ]:
dfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   id      4 non-null      float64
 2   salary  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
dfl.dropna()

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0

In [ ]:
dfl

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [ ]:
dfl.fillna(value = 'abc')

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      abc  105.0  30000.0

In [ ]:
dfl

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [ ]:
dfl.drop([2],axis=0,inplace=True)
dfl

   name     id   salary
0    rk  102.0  15000.0
1  rama  103.0  20000.0
3   NaN  105.0  30000.0

In [ ]:
dfl

   name     id   salary
0    rk  102.0  15000.0
1  rama  103.0  20000.0
3   NaN  105.0  30000.0


### Groupby

<img src="https://th.bing.com/th/id/OIP.h5V2-wp2jL4Ip5FTRd6ThQAAAA?pid=ImgDet&rs=1">

In [ ]:
import pandas as pd
df = pd.DataFrame({'Animal' : ['Falcon', 'Falcon','Parrot', 'Parrot'],'Max Speed' : [380., 370., 24., 26.],'wind Speed' : [380., 370., 24., 26.]})
df

   Animal  Max Speed  wind Speed
0  Falcon      380.0       380.0
1  Falcon      370.0       370.0
2  Parrot       24.0        24.0
3  Parrot       26.0        26.0

In [ ]:
df.groupby(['Animal']).mean()

        Max Speed  wind Speed
Animal
Falcon      375.0       375.0
Parrot       25.0        25.0

In [ ]:
# Transpose
df.T

                 0       1       2       3
Animal      Falcon  Falcon  Parrot  Parrot
Max Speed    380.0   370.0    24.0    26.0
wind Speed   380.0   370.0    24.0    26.0

### Get Dummies

In [ ]:
import pandas as pd

data = {'firstname': ['Arun', 'Jebu', 'Venkat', 'Rekha', 'Majid','Mohsin'],
        'lastname': ['Kumar', 'Jacob', 'Raghavan', 'Singh', 'Khan','Khan'],
        'employmenttype': ['Service', 'Business', 'Student', 'Service', 'Business','Business'],
        'country' :['India','USA','USA','Sweden','Australia','Germany']}


df = pd.DataFrame(data, columns = ['firstname','lastname','employmenttype','country'])

print(df)

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

In [ ]:
# Apply pd.get_dummies to 'employmenttype' and 'country' columns
df1 = pd.get_dummies(df['employmenttype'], dtype=int)
df2 = pd.get_dummies(df['country'], dtype=int)
print(df1)
print(df2)

   Business  Service  Student
0         0        1        0
1         1        0        0
2         0        0        1
3         0        1        0
4         1        0        0
5         1        0        0
   Australia  Germany  India  Sweden  USA
0          0        0      1       0    0
1          0        0      0       0    1
2          0        0      0       0    1
3          0        0      0       1    0
4          1        0      0       0    0
5          0        1      0       0    0

In [ ]:
df

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

## concatination

In [ ]:
import pandas as pd
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [ ]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:
df = pd.concat([india_weather, us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:
# ignore index
df = pd.concat([india_weather, us_weather], ignore_index=True)

df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [ ]:
import pandas as pd
emp = {"Name": ["Parker", "Smith", "William", "Parker"],
"Age": [21, 32, 29, 21]}
info = pd.DataFrame(emp)
print(info)
print("--------------------")
info = info.drop_duplicates()
print(info)

      Name  Age
0   Parker   21
1    Smith   32
2  William   29
3   Parker   21
--------------------
      Name  Age
0   Parker   21
1    Smith   32
2  William   29

<h1>Apply<h1>

In [ ]:
def calc_sum(kiran):
    return kiran+1
data = {
  "x": [50, 40, 30],
  "y": [300, 1112, 42]
}
df = pd.DataFrame(data)
print(df)
x = df.apply(calc_sum)
print(x)

    x     y
0  50   300
1  40  1112
2  30    42
    x     y
0  51   301
1  41  1113
2  31    43

In [ ]:
import pandas as pd

# Create a sample DataFrame with a 'Gender' column
data = {
    'Name': ['John', 'Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Gender': ['Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'Age': [23, 35, 45, 40, 28, 33],
    'group':["cse","ece","eee","cse","ece","ece"],
}

df1 = pd.DataFrame(data)

df1

      Name  Gender  Age group
0     John    Male   23   cse
1    Alice  Female   35   ece
2      Bob    Male   45   eee
3  Charlie    Male   40   cse
4    David  Female   28   ece
5      Eva  Female   33   ece

In [ ]:
# Convert 'Gender' column to categorical data
d = pd.Categorical(df1['group'])

# Print the categorical data
print(d)

['cse', 'ece', 'eee', 'cse', 'ece', 'ece']
Categories (3, object): ['cse', 'ece', 'eee']

In [ ]:
!pip install kagglehub



import kagglehub

# Download latest version
path = kagglehub.dataset_download("abhijitdahatonde/zomato-restaurants-dataset")

print("Path to dataset files:", path)

Collecting kagglehub
  Downloading kagglehub-0.3.12-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (2.32.3)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2025.4.26)
Requirement already satisfied: colorama in c:\users\tarak\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-0.3.12-py3-none-any.whl (67 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, kagglehub
Successfully installed kagglehub-0.3.12 tqdm-4.67.1

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
C:\Users\tarak\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\tarak\.cache\kagglehub\datasets\abhijitdahatonde\zomato-restaurants-dataset\versions\1

In [ ]:
print("Path to dataset files:", path)

Path to dataset files: C:\Users\tarak\.cache\kagglehub\datasets\abhijitdahatonde\zomato-restaurants-dataset\versions\1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("C:\\Users\\tarak\\.cache\\kagglehub\\datasets\\abhijitdahatonde\\zomato-restaurants-dataset\\versions\\1\\zomato.csv",delimiter=',')
data

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [ ]:
data.head()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [ ]:
data.tail()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB

In [ ]:
data.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [ ]:
data.dropna()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [ ]:
data.to_csv('preprocessed_data.csv')  #to save the preprocessed data use .to_csv() method

In [ ]:
get_dummies() is a pandas function used to convert categorical data into numerical data.
Most machine learning models and some operations need data in numerical format, but sometimes we have categories.
It helps machine learning algorithms understand non-numeric data by turning them into 0s and 1s.

In [ ]:
dfl

   name     id   salary
0    rk  102.0  15000.0
1  rama  103.0  20000.0
3   NaN  105.0  30000.0